POST http://127.0.0.1:3000/api/auth/registro
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321",
    "username": "admin"
}

### Login
POST http://127.0.0.1:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin2@mail.com",
    "password": "admin54321"
}

### Perfil

GET http://127.0.0.1:3000/api/auth/perfil
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbjJAbWFpbC5jb20iLCJ0aW1lIjoiMjAyMi0wNy0xM1QyMjo1ODoxNy40MTJaIiwiaWF0IjoxNjU3NzUzMDk3LCJleHAiOjE2NTc3NTY2OTd9.3niIkF40_x74EjouztuywLKObFuEjLr4UtpHFr1ie0k
